# -*- coding: utf-8 -*-
"""Shopping.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vASoqWn2mPpqBdgdMxrC10nGeCawfWyN
"""

#Imports
#External package need to install
!pip install apyori
#import all required packages..
import pandas as pd
import numpy as np
from apyori import apriori

#loading market basket dataset..

df = pd.read_csv('/content/DMV302_Assessment_2_shoppingtransactions.csv',header=None)
df.head()

#replacing empty value with 0.
df.fillna(0,inplace=True)
df.head()

#convert data in list format
transactions = []
for i in range(0,len(df)):
    transactions.append([str(df.values[i,j]) for j in range(0,20) if str(df.values[i,j])!='0'])

transactions[0]

#Call apriori function which requires minimum support, confidance and lift
rules = apriori(transactions,min_support=0.003,min_confidance=0.2,min_lift=3,min_length=2)

# all rules need to be converted in a list..
Results = list(rules)

#convert result in a dataframe for further operation...
df_results = pd.DataFrame(Results)

# as we see order statistics itself a list so need to be converted in proper format..
df_results.head()

#keep support in a separate data frame so we can use later.. 
support = df_results.support

#all four empty list which will contain lhs, rhs, confidance and lift respectively.

first_values = []
second_values = []
third_values = []
fourth_value = []

# loop number of rows time and append 1 by 1 value in a separate list.. first and second element was frozenset which need to be converted in list..
for i in range(df_results.shape[0]):
    single_list = df_results['ordered_statistics'][i][0]
    first_values.append(list(single_list[0]))
    second_values.append(list(single_list[1]))
    third_values.append(single_list[2])
    fourth_value.append(single_list[3])

#convert all four list into dataframe for further operation..
lhs = pd.DataFrame(first_values)
rhs= pd.DataFrame(second_values)
confidance=pd.DataFrame(third_values,columns=['Confidance'])
lift=pd.DataFrame(fourth_value,columns=['lift'])

#concat all list together in a single dataframe
df_final = pd.concat([lhs,rhs,support,confidance,lift], axis=1)
df_final

df_final.fillna(value=' ', inplace=True)

df_final

#@title Association Menu
Sup = "" #@param {type:"string"}
Con = "" #@param {type:"string"}
Exit = False #@param {type:"boolean"}
item1 = "" #@param {type:"string"}
item2 = "" #@param {type:"string"}